### ISSUE TITLE
Allow to ingest arrays larger than 2 GB

### ISSUE THREAD

**Issue by FrancescAlted** [Blosc/python-blosc2#49]
This script shows the issue:

```
import numpy as np
import blosc2


# N = 50_000  # this works!
N = 80_000   # this does not...
nsplits = 10
chunks = N // nsplits

x = np.eye(N)
cparams = {"typesize": 8}
storage = {"contiguous": True, "urlpath": "eye5.b2frame"}
schunk = blosc2.SChunk(data=x, mode="w", chunksize=chunks * N * 8, cparams=cparams, **storage)

schunk = blosc2.open("eye5.b2frame")

c = np.empty(chunks * N).reshape(chunks, N)
total = 0
for i in range(nsplits):
    schunk.decompress_chunk(i, c)
    total += c.sum()

print("Total sum:", total)
```

This gives the next error:

```
Traceback (most recent call last):
  File "/home/faltet2/blosc/python-blosc2/bench/read-binary-data6.py", line 12, in <module>
    schunk = blosc2.SChunk(data=x, mode="w", chunksize=chunks * N * 8, cparams=cparams, **storage)
  File "/home/faltet2/blosc/python-blosc2/blosc2/SChunk.py", line 88, in __init__
    super(SChunk, self).__init__(schunk=sc, chunksize=chunksize, data=data, mode=mode, **kwargs)
  File "blosc2_ext.pyx", line 721, in blosc2.blosc2_ext.SChunk.__init__
OverflowError: value too large to convert to int32_t
```

whereas it should be:

```
Total sum: 80000.0
```

BTW, I don't think it is a good idea to add this as a test, because it can take too much memory (> 4 GB).  Or maybe marking it as `heavy` ?

**Comment by FrancescAlted** [comment]
Oops, the problem is that the chunksize is too large here, so we can close this.  At any rate, I think that raising a `ValueError` when the chunksize is larger than `2**31 - 1` (aka INT32_MAX) is a better error message.  Can you do that?

**Comment by martaiborra** [comment]
Sure! Done in eaf4702f9142c682e95bfb23152364daacb73d78.
